// Source of truth for the initial product catalog. Loaded into Postgres by seed.js.
export const PRODUCTS = [
  {
    id: 'p1',
    name: 'Wireless Noise-Cancelling Headphones',
    category: 'Electronics',
    price: 89.99,
    rating: 4.5,
    stock: 24,
    emoji: '🎧',
    color: '#2b2d42',
    description:
      'Over-ear Bluetooth headphones with active noise cancellation and 30-hour battery life.',
  },
  {
    id: 'p2',
    name: 'Smartwatch Series X',
    category: 'Electronics',
    price: 149.0,
    rating: 4.2,
    stock: 12,
    emoji: '⌚',
    color: '#1d3557',
    description:
      'Track your workouts, heart rate, and notifications with this sleek smartwatch.',
  },
  {
    id: 'p3',
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 39.5,
    rating: 4.0,
    stock: 40,
    emoji: '🔊',
    color: '#457b9d',
    description: 'Compact speaker with rich bass and 12-hour playtime, water resistant.',
  },
  {
    id: 'p4',
    name: '65" 4K Smart TV',
    category: 'Electronics',
    price: 699.99,
    rating: 4.7,
    stock: 6,
    emoji: '📺',
    color: '#0b132b',
    description: 'Crisp 4K resolution with built-in streaming apps and voice remote.',
  },
  {
    id: 'p5',
    name: "Men's Slim Fit Denim Jacket",
    category: 'Fashion',
    price: 54.99,
    rating: 4.1,
    stock: 30,
    emoji: '🧥',
    color: '#3a5a40',
    description: 'Classic denim jacket with a modern slim fit, perfect for layering.',
  },
  {
    id: 'p6',
    name: "Women's Running Shoes",
    category: 'Fashion',
    price: 72.0,
    rating: 4.6,
    stock: 18,
    emoji: '👟',
    color: '#d62828',
    description: 'Lightweight breathable running shoes with responsive cushioning.',
  },
  {
    id: 'p7',
    name: 'Classic Leather Handbag',
    category: 'Fashion',
    price: 120.0,
    rating: 4.4,
    stock: 9,
    emoji: '👜',
    color: '#6d597a',
    description: 'Genuine leather handbag with adjustable strap and multiple compartments.',
  },
  {
    id: 'p8',
    name: 'Unisex Aviator Sunglasses',
    category: 'Fashion',
    price: 24.99,
    rating: 4.0,
    stock: 50,
    emoji: '🕶️',
    color: '#22223b',
    description: 'UV-protective aviator sunglasses with a timeless design.',
  },
  {
    id: 'p9',
    name: '12-Piece Non-Stick Cookware Set',
    category: 'Home & Kitchen',
    price: 159.99,
    rating: 4.8,
    stock: 8,
    emoji: '🍳',
    color: '#bc6c25',
    description: 'Durable non-stick cookware set including pots, pans, and lids.',
  },
  {
    id: 'p10',
    name: 'Robot Vacuum Cleaner',
    category: 'Home & Kitchen',
    price: 249.0,
    rating: 4.3,
    stock: 14,
    emoji: '🤖',
    color: '#3d5a80',
    description: 'Smart robot vacuum with mapping technology and app control.',
  },
  {
    id: 'p11',
    name: 'Memory Foam Pillow (2-Pack)',
    category: 'Home & Kitchen',
    price: 34.99,
    rating: 4.5,
    stock: 60,
    emoji: '🛏️',
    color: '#7f5539',
    description: 'Ergonomic memory foam pillows for improved neck and back support.',
  },
  {
    id: 'p12',
    name: 'Stainless Steel Coffee Maker',
    category: 'Home & Kitchen',
    price: 89.0,
    rating: 4.2,
    stock: 20,
    emoji: '☕',
    color: '#6f1d1b',
    description: 'Brew up to 12 cups with programmable timer and auto shut-off.',
  },
  {
    id: 'p13',
    name: 'The Silent Mountain (Novel)',
    category: 'Books',
    price: 14.99,
    rating: 4.6,
    stock: 100,
    emoji: '📖',
    color: '#283618',
    description: 'A gripping bestselling thriller set in the remote Himalayas.',
  },
  {
    id: 'p14',
    name: 'Cooking for Beginners',
    category: 'Books',
    price: 19.99,
    rating: 4.3,
    stock: 45,
    emoji: '📗',
    color: '#606c38',
    description: 'Easy step-by-step recipes for anyone starting their cooking journey.',
  },
  {
    id: 'p15',
    name: 'Atomic Habits Workbook',
    category: 'Books',
    price: 16.5,
    rating: 4.9,
    stock: 70,
    emoji: '📘',
    color: '#003049',
    description: 'A practical companion workbook for building better daily habits.',
  },
  {
    id: 'p16',
    name: 'Yoga Mat with Carry Strap',
    category: 'Sports',
    price: 27.99,
    rating: 4.4,
    stock: 55,
    emoji: '🧘',
    color: '#588157',
    description: 'Non-slip, eco-friendly yoga mat, extra thick for joint support.',
  },
  {
    id: 'p17',
    name: 'Adjustable Dumbbell Set',
    category: 'Sports',
    price: 189.99,
    rating: 4.7,
    stock: 10,
    emoji: '🏋️',
    color: '#495057',
    description: 'Space-saving adjustable dumbbells, 5-52.5 lbs per dumbbell.',
  },
  {
    id: 'p18',
    name: 'Insulated Water Bottle 1L',
    category: 'Sports',
    price: 22.0,
    rating: 4.5,
    stock: 80,
    emoji: '🚰',
    color: '#0077b6',
    description: 'Keeps drinks cold for 24 hours or hot for 12 hours.',
  },
  {
    id: 'p19',
    name: 'Vitamin C Serum',
    category: 'Beauty',
    price: 18.99,
    rating: 4.3,
    stock: 65,
    emoji: '🧴',
    color: '#e85d04',
    description: 'Brightening facial serum with hyaluronic acid for glowing skin.',
  },
  {
    id: 'p20',
    name: 'Professional Hair Dryer',
    category: 'Beauty',
    price: 45.0,
    rating: 4.1,
    stock: 22,
    emoji: '💇',
    color: '#9d4edd',
    description: 'Fast-drying ionic hair dryer with multiple heat and speed settings.',
  },
  {
    id: 'p21',
    name: 'Matte Lipstick Set (6 Colors)',
    category: 'Beauty',
    price: 29.99,
    rating: 4.6,
    stock: 38,
    emoji: '💄',
    color: '#c9184a',
    description: 'Long-lasting matte lipstick set in six versatile shades.',
  },
]
